apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  type: NodePort
  selector:
    app: sample-python-app
  ports:
    - port: 90
      targetPort: 8000 # port on which app is running
      nodePort: 30007